FROM nvcr.io/nvidia/pytorch:22.12-py3

WORKDIR /workspace/
ENV PYTHONPATH /workspace/
COPY $PWD/api-for-open-llm/requirements.txt /workspace/
COPY $PWD/api-for-open-llm/ /workspace

RUN pip install --no-cache-dir -r /workspace/requirements.txt -i https://mirror.baidu.com/pypi/simple
RUN pip install bitsandbytes --upgrade -i https://mirror.baidu.com/pypi/simple && \
    pip install torch -U -i https://mirror.baidu.com/pypi/simple && \
    pip install vllm>=0.1.4 && \
    pip uninstall transformer-engine -y
